const stateDistricts = {
  "Andaman and Nicobar Island": [
    "NICOBARS",
    "NORTH AND MIDDLE ANDAMAN",
    "SOUTH ANDAMANS",
  ],
  "Andhra Pradesh": [
    "ADILABAD",
    "ANANTAPUR",
    "CHITTOOR",
    "EAST GODAVARI",
    "GUNTUR",
    "HYDERABAD",
    "KADAPA",
    "KARIMNAGAR",
    "KHAMMAM",
    "KRISHNA",
    "KURNOOL",
    "MAHBUBNAGAR",
    "MEDAK",
    "NALGONDA",
    "NIZAMABAD",
    "PRAKASAM",
    "RANGAREDDI",
    "SPSR NELLORE",
    "SRIKAKULAM",
    "VISAKHAPATANAM",
    "VIZIANAGARAM",
    "WARANGAL",
    "WEST GODAVARI",
  ],
  "Arunachal Pradesh": [
    "ANJAW",
    "CHANGLANG",
    "DIBANG VALLEY",
    "EAST KAMENG",
    "EAST SIANG",
    "KAMLE",
    "KRA DAADI",
    "KURUNG KUMEY",
    "LEPARADA",
    "LOHIT",
    "LONGDING",
    "LOWER DIBANG VALLEY",
    "LOWER SIANG",
    "LOWER SUBANSIRI",
    "NAMSAI",
    "PAKKE KESSANG",
    "PAPUM PARE",
    "SHI YOMI",
    "SIANG",
    "TAWANG",
    "TIRAP",
    "UPPER SIANG",
    "UPPER SUBANSIRI",
    "WEST KAMENG",
    "WEST SIANG",
  ],
  Assam: [
    "BAKSA",
    "BARPETA",
    "BISWANATH\n",
    "BONGAIGAON",
    "CACHAR",
    "CHARAIDEO\n",
    "CHIRANG",
    "DARRANG",
    "DHEMAJI",
    "DHUBRI",
    "DIBRUGARH",
    "DIMA HASAO",
    "GOALPARA",
    "GOLAGHAT",
    "HAILAKANDI",
    "HOJAI\n",
    "JORHAT",
    "KAMRUP",
    "KAMRUP METRO",
    "KARBI ANGLONG",
    "KARIMGANJ",
    "KOKRAJHAR",
    "LAKHIMPUR",
    "MAJULI\n",
    "MARIGAON",
    "NAGAON",
    "NALBARI",
    "SIVASAGAR",
    "SONITPUR",
    "SOUTH SALMARA MANCACHAR\n",
    "TINSUKIA",
    "UDALGURI",
    "WEST KARBI ANGLONG\n",
  ],
  Bihar: [
    "ARARIA",
    "ARWAL",
    "AURANGABAD",
    "BANKA",
    "BEGUSARAI",
    "BHAGALPUR",
    "BHOJPUR",
    "BOKARO",
    "BUXAR",
    "CHATRA",
    "DARBHANGA",
    "DEOGHAR",
    "DHANBAD",
    "DUMKA",
    "EAST SINGHBUM",
    "GARHWA",
    "GAYA",
    "GIRIDIH",
    "GODDA",
    "GOPALGANJ",
    "GUMLA",
    "HAZARIBAGH",
    "JAMUI",
    "JEHANABAD",
    "KAIMUR (BHABUA)",
    "KATIHAR",
    "KHAGARIA",
    "KISHANGANJ",
    "KODERMA",
    "LAKHISARAI",
    "LOHARDAGA",
    "MADHEPURA",
    "MADHUBANI",
    "MUNGER",
    "MUZAFFARPUR",
    "NALANDA",
    "NAWADA",
    "PAKUR",
    "PALAMU",
    "PASHCHIM CHAMPARAN",
    "PATNA",
    "PURBI CHAMPARAN",
    "PURNIA",
    "RANCHI",
    "ROHTAS",
    "SAHARSA",
    "SAHEBGANJ",
    "SAMASTIPUR",
    "SARAN",
    "SHEIKHPURA",
    "SHEOHAR",
    "SITAMARHI",
    "SIWAN",
    "SUPAUL",
    "VAISHALI",
    "WEST SINGHBHUM",
  ],
  CHANDIGARH: ["CHANDIGARH"],
  Chhattisgarh: [
    "BALOD",
    "BALODA BAZAR",
    "BALRAMPUR",
    "BASTAR",
    "BEMETARA",
    "BIJAPUR",
    "BILASPUR",
    "DANTEWADA",
    "DHAMTARI",
    "DURG",
    "GARIYABAND",
    "GAURELLA-PENDRA-MARWAHI",
    "JANJGIR-CHAMPA",
    "JASHPUR",
    "KABIRDHAM",
    "KANKER",
    "KONDAGAON",
    "KORBA",
    "KOREA",
    "MAHASAMUND",
    "MUNGELI",
    "NARAYANPUR",
    "RAIGARH",
    "RAIPUR",
    "RAJNANDGAON",
    "SUKMA",
    "SURAJPUR",
    "SURGUJA",
  ],
  "Dadra and Nagar Haveli": ["DADRA AND NAGAR HAVELI"],
  "Daman and Diu": ["DAMAN", "DIU"],
  Delhi: ["DELHI_TOTAL"],
  Goa: ["NORTH GOA", "SOUTH GOA"],
  Gujarat: [
    "AHMADABAD",
    "AMRELI",
    "ANAND",
    "ARAVALLI",
    "BANAS KANTHA",
    "BHARUCH",
    "BHAVNAGAR",
    "BOTAD",
    "CHHOTAUDEPUR",
    "DANG",
    "DEVBHUMI DWARKA",
    "DOHAD",
    "GANDHINAGAR",
    "GIR SOMNATH",
    "JAMNAGAR",
    "JUNAGADH",
    "KACHCHH",
    "KHEDA",
    "MAHESANA",
    "MAHISAGAR",
    "MORBI",
    "NARMADA",
    "NAVSARI",
    "PANCH MAHALS",
    "PATAN",
    "PORBANDAR",
    "RAJKOT",
    "SABAR KANTHA",
    "SURAT",
    "SURENDRANAGAR",
    "TAPI",
    "VADODARA",
    "VALSAD",
  ],
};
